#!/usr/bin/env sh

# (ctrl -x is the preparatory command - from in sxiv) then keys below to execute

stash="${HOME}/stash"
while read file
do
        case "$1" in
    "c") n=0
         cp ${file} ${stash}
         ((n++)) ;;
    "w") cp -f "$file" /home/slappy/.config/background/bg.jpg ;;
    "r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"y")
		echo -n "$file" | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")
		readlink -f "$file" | xclip -selection clipboard &&
		notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"d")
		[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
	"g")	ifinstalled gimp && gimp "$file" & ;;
        esac
done
